---
title: "Reporte compartido ER - SF"
format: 
  html:
    editor: visual
    toc: true
    toc-title: "Índice"
    toc-depth: 3
    toc-location: left
execute: 
  warning: false
  message: false
  echo: false
---

# Introducción

Las infecciones respiratorias agudas (IRAs) constituyen una importante causa de morbimortalidad afectando fundamentalmente a niñas/os menores de cinco años, particularmente aquellos menores de 2 años, adultos mayores (\> 60 años) y personas con comorbilidades de riesgo para IRA grave (patología cardiovascular, respiratoria, inmunosupresión, entre otras).

La estrategia propuesta por OPS de vigilancia centinela implica la recolección de datos en forma sistemática y oportuna, a través de un número limitado de establecimientos seleccionados en base a ciertos criterios preespecificados.

Este informe es generado de manera conjunta por los equipos de Entre Rios y Santa Fe, con el objetivo de analizar las características clínicas, epidemiológicas y laboratoriales de casos internados con diagnóstico de Infección Respiratoria Aguda Grave (IRAG) e IRAG extendida, en Unidades Centinelas provinciales.

```{r}
#| message: false
#| warning: false
#| include: false

source('analisis/leer_base.R')
source('analisis/curvas_sem.R')
source('analisis/grupos_edad.R')
source('analisis/determinaciones.R')

```
